title: Indirect Link
tagline: A way for skeptics to share links without falling foul of overly aggressive social media filters
#summary: A way for skeptics to share links without falling foul of overly aggressive social media filters
#description: A way for skeptics to share links without falling foul of overly aggressive social media filters
#url: https://indirect.link
permalink: /:title
remote_theme: jonaharagon/jekyll-bootstrap-theme
timezone: Pacific/Auckland
author:
  name: Mark Honeychurch
  email: mark@honeychurch.org
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
